format:
  html:
    toc: true
    toc-depth: 4
    toc-expand: 2
    toc-location: left
    code-fold: true
    code-summary: "Show code"
    theme: cosmo
    fig-cap-location: top
    df-print: paged
    page-layout: full
